package map;

public enum ConveyorBelt {
    CONVEYOR_NORTH,
    CONVEYOR_SOUTH,
    CONVEYOR_EAST,
    CONVEYOR_WEST,
    EXPRESS_CONVEYOR_NORTH,
    EXPRESS_CONVEYOR_SOUTH,
    EXPRESS_CONVEYOR_EAST,
    EXPRESS_CONVEYOR_WEST
}
